name: ReservationDown
version: '${version}'
main: org.example.pluhin.reservationdown.ReservationDown
api-version: '1.20'
commands:
  shutdown:
    usage: /shutdown <set|remove|check> <Hour|minute|second> <time>